FROM oven/bun:1.3.11

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 make g++ nodejs npm && \
    rm -rf /var/lib/apt/lists/*

COPY package.json ./
RUN bun install

COPY . .

EXPOSE 3000

CMD ["bun","run","dev"]
